// Copyright 2026 Pipeline Builder Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Build the YAML body. Kept inline (no template-file lookup) so this
 * endpoint works in every deploy posture without filesystem access. The
 * platform container does not need to mount the deploy templates dir.
 * Mirror changes here when those template files change.
 */
export function renderManifest(vars: { slug: string; nsName: string; createdAt: string }): string {
  const { slug, nsName, createdAt } = vars;
  // String-array join keeps the YAML free of JS-template-literal escaping
  // quirks. Each entry is one YAML document; we join with the standard
  // separator so kubectl apply reads them as a multi-doc stream.
  const docs: string[] = [];

  docs.push(
    '# Generated by Pipeline Builder for org "' + slug + '" at ' + createdAt + '.\n'
    + '# Apply: kubectl apply -f <this-file>\n'
    + '# Tear down: kubectl delete namespace ' + nsName,
  );

  docs.push(
    'apiVersion: v1\n'
    + 'kind: Namespace\n'
    + 'metadata:\n'
    + '  name: ' + nsName + '\n'
    + '  labels:\n'
    + '    app.kubernetes.io/part-of: pipeline-builder\n'
    + '    pipeline-builder.io/org-slug: ' + slug + '\n'
    + '    pipeline-builder.io/tier: enterprise\n'
    + '  annotations:\n'
    + '    pipeline-builder.io/created-at: "' + createdAt + '"',
  );

  docs.push(
    'apiVersion: v1\n'
    + 'kind: ServiceAccount\n'
    + 'metadata:\n'
    + '  name: org-workload\n'
    + '  namespace: ' + nsName + '\n'
    + '  labels:\n'
    + '    pipeline-builder.io/org-slug: ' + slug,
  );

  // Default-deny: combined with the allow-list below, gives the org's
  // workloads the most restrictive default consistent with letting them
  // function at all.
  docs.push(
    'apiVersion: networking.k8s.io/v1\n'
    + 'kind: NetworkPolicy\n'
    + 'metadata:\n'
    + '  name: default-deny\n'
    + '  namespace: ' + nsName + '\n'
    + 'spec:\n'
    + '  podSelector: {}\n'
    + '  policyTypes: ["Ingress", "Egress"]',
  );

  docs.push(
    'apiVersion: networking.k8s.io/v1\n'
    + 'kind: NetworkPolicy\n'
    + 'metadata:\n'
    + '  name: allow-egress-infra\n'
    + '  namespace: ' + nsName + '\n'
    + 'spec:\n'
    + '  podSelector: {}\n'
    + '  policyTypes: ["Egress"]\n'
    + '  egress:\n'
    + '    - to:\n'
    + '        - namespaceSelector:\n'
    + '            matchLabels:\n'
    + '              kubernetes.io/metadata.name: kube-system\n'
    + '          podSelector:\n'
    + '            matchLabels:\n'
    + '              k8s-app: kube-dns\n'
    + '      ports:\n'
    + '        - port: 53\n'
    + '          protocol: UDP\n'
    + '    - to:\n'
    + '        - namespaceSelector:\n'
    + '            matchLabels:\n'
    + '              kubernetes.io/metadata.name: pipeline-builder\n'
    + '      ports:\n'
    + '        - port: 5432\n'
    + '        - port: 6379\n'
    + '        - port: 3000\n'
    + '        - port: 3100\n'
    + '        - port: 5000\n'
    + '    - to:\n'
    + '        - ipBlock:\n'
    + '            cidr: 0.0.0.0/0\n'
    + '            except:\n'
    + '              - 10.0.0.0/8\n'
    + '              - 172.16.0.0/12\n'
    + '              - 192.168.0.0/16\n'
    + '      ports:\n'
    + '        - port: 443',
  );

  docs.push(
    'apiVersion: networking.k8s.io/v1\n'
    + 'kind: NetworkPolicy\n'
    + 'metadata:\n'
    + '  name: allow-ingress-from-ingress-controller\n'
    + '  namespace: ' + nsName + '\n'
    + 'spec:\n'
    + '  podSelector: {}\n'
    + '  policyTypes: ["Ingress"]\n'
    + '  ingress:\n'
    + '    - from:\n'
    + '        - namespaceSelector:\n'
    + '            matchLabels:\n'
    + '              kubernetes.io/metadata.name: ingress-nginx',
  );

  // Baseline enterprise-tier ResourceQuota. Larger contracts get a custom
  // override applied separately (kubectl edit resourcequota -n <ns> ...).
  docs.push(
    'apiVersion: v1\n'
    + 'kind: ResourceQuota\n'
    + 'metadata:\n'
    + '  name: org-quota\n'
    + '  namespace: ' + nsName + '\n'
    + 'spec:\n'
    + '  hard:\n'
    + '    pods: "50"\n'
    + '    requests.cpu: "20"\n'
    + '    requests.memory: "40Gi"\n'
    + '    limits.cpu: "40"\n'
    + '    limits.memory: "80Gi"\n'
    + '    persistentvolumeclaims: "10"',
  );

  docs.push(
    'apiVersion: v1\n'
    + 'kind: LimitRange\n'
    + 'metadata:\n'
    + '  name: org-limits\n'
    + '  namespace: ' + nsName + '\n'
    + 'spec:\n'
    + '  limits:\n'
    + '    - type: Container\n'
    + '      default:\n'
    + '        cpu: "500m"\n'
    + '        memory: "1Gi"\n'
    + '      defaultRequest:\n'
    + '        cpu: "100m"\n'
    + '        memory: "256Mi"\n'
    + '      max:\n'
    + '        cpu: "4"\n'
    + '        memory: "8Gi"\n'
    + '      min:\n'
    + '        cpu: "50m"\n'
    + '        memory: "64Mi"',
  );

  return docs.join('\n---\n') + '\n';
}
