AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Runtime: nodejs22.x

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: stage

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: service/
      Handler: app.handler
      {%- if cookiecutter.architectures.value != []%}
      Architectures:
      {%- for arch in cookiecutter.architectures.value %}
        - {{arch}}
      {%- endfor %}
      {%- endif %}
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /{{ cookiecutter.project_name }}
            Method: get
            ApiId:
              Ref: HttpApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  Api:
    Description: "API Gateway endpoint URL for function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/stage/hello/"
  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
  LambdaFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt LambdaFunctionRole.Arn
