AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Handler: index.handler
    Layers:
      - !Ref shared
    Runtime: nodejs22.x
    MemorySize: 128
    Timeout: 15
  
Resources:
  api:
    Type: AWS::Serverless::HttpApi

  shared:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-dependencies
      CompatibleRuntimes:
        - nodejs22.x
      ContentUri: src/layers/shared/nodejs/
    Metadata:
      BuildMethod: nodejs22.x

Outputs:
  Api:
    Description: "API Gateway URL for function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/hello/"
