services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './api.conf:/etc/nginx/conf.d/api.conf'
  database:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - '15432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pipeline_builder
    command: postgres -c listen_addresses='*'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './db-data/:/var/lib/postgresql/data/'
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin
    ports:
      - '15433:80'
    environment:
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: mwashburn160@gmail.com
    volumes:
      - './pgadmin-data/:/var/lib/pgadmin/'
  add-plugin:
      build:
        context: ../../api/backend/add-plugin
        dockerfile: Dockerfile
      container_name: add-plugin
      privileged: true
      ports:
        - '3000:3000'