services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    depends_on:
      - add-plugin
    ports:
      - '8080:80'
    restart: always
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './api.conf:/etc/nginx/conf.d/api.conf:ro'
  database:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= password
      - POSTGRES_DB=pipeline_builder
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    restart: always
    command: postgres -c listen_addresses='*'
    volumes:
      - './db-data/:/var/lib/postgresql/data/'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DEFAULT_EMAIL=mwashburn160@gmail.com
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '5433:80'
    volumes:
      - './pgadmin-data/:/var/lib/pgadmin/'
  add-plugin:
    image: add-plugin
    build:
      context: ../../api/backend/add-plugin
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=pipeline_builder
    privileged: true
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '3000:3000'
