version: '3.7'
services:
  database:
    image: 'postgres:17.4'
    container_name: postgres
    ports:
      - '15432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pipeline_builder
    networks:
      - postgres-network
    command: postgres -c listen_addresses='*'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './db-data/:/var/lib/postgresql/data/'
  pgadmin:
    image: 'dpage/pgadmin4:2025-04-28-1'
    container_name: pgadmin
    ports:
      - '15433:80'
    environment:
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: mwashburn160@gmail.com
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - './pgadmin-data/:/var/lib/pgadmin/'
networks:
  postgres-network:
    driver: bridge
