version: '3.7'
services:
  database:
    image: 'postgres:17.4'
    container_name: postgres
    ports:
      - '15432:5432'
    restart: always
    env_file:
      - .config
    networks:
      - postgres-network
    command: postgres -c listen_addresses='*' 
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      interval: 15s
      timeout: 5s
      retries: 3
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './db-data/:/var/lib/postgresql/data/'
  pgadmin:
    image: 'dpage/pgadmin4:2025-04-28-1'
    container_name: pgadmin
    ports:
      - '15433:80'
    env_file:
      - .config
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - './pgadmin-data/:/var/lib/pgadmin/'
networks:
  postgres-network:
    driver: bridge
