apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# EC2 — standalone manifests for AWS EC2 deployment.

namespace: pipeline-builder

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - resource-limits.yaml
  - mongodb.yaml
  - postgres.yaml
  - redis.yaml
  - ollama.yaml
  - nginx.yaml
  - platform.yaml
  - pipeline.yaml
  - plugin.yaml
  - message.yaml
  - reporting.yaml
  - quota.yaml
  - billing.yaml
  - frontend.yaml
  - mongo-express.yaml
  - pgadmin.yaml
  - registry.yaml
  - registry-express.yaml
  - prometheus.yaml
  - loki.yaml
  - grafana.yaml
  - promtail.yaml
