// Copyright 2026 Pipeline Builder Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * File-backed ES256 signer — the docker and minikube targets, and any install
 * without KMS.
 *
 * The private key is a PEM on disk: a bind-mounted file under compose, a
 * Kubernetes Secret mounted as a file on the k8s targets. Generated by
 * `deploy/bin/token-signing-keys.sh` (`openssl ecparam -name prime256v1 …`),
 * which leaves it mode 644 like the other mounted key material — see
 * docs/runbooks/secret-rotation.md.
 *
 * Signing is local and synchronous under the hood; the async signature exists so
 * the KMS implementation can satisfy the same interface.
 */

import crypto, { type KeyObject } from 'crypto';
import { readFile } from 'fs/promises';
import { createLogger, publicJwkFrom, USER_TOKEN_CURVE, errorMessage } from '@pipeline-builder/api-core';
import type { SigningKey } from './signer.js';

const logger = createLogger('token-signing-local');

/**
 * Load one PEM private key and project it onto a {@link SigningKey}.
 *
 * `canSign: false` yields a verification-only key — that is how a retiring key
 * stays published without being able to mint anything new.
 */
export async function loadLocalSigningKey(path: string, opts: { canSign: boolean }): Promise<SigningKey> {
  let pem: string;
  try {
    pem = await readFile(path, 'utf-8');
  } catch (error) {
    throw new Error(`Token signing key file ${path} could not be read: ${errorMessage(error)}`);
  }

  let privateKey: KeyObject;
  try {
    privateKey = crypto.createPrivateKey(pem);
  } catch (error) {
    throw new Error(`Token signing key file ${path} is not a readable private key: ${errorMessage(error)}`);
  }
  if (privateKey.asymmetricKeyType !== 'ec') {
    throw new Error(`Token signing key ${path} must be an EC ${USER_TOKEN_CURVE} key (got ${privateKey.asymmetricKeyType ?? 'unknown'})`);
  }

  const publicKey = crypto.createPublicKey(privateKey);
  // Throws unless the key really is P-256, so a wrong curve fails at boot
  // rather than producing tokens nothing in the fleet can verify.
  const { kid } = publicJwkFrom(publicKey);
  logger.info('Loaded local token signing key', { path, kid, canSign: opts.canSign });

  return {
    kid,
    publicKey,
    ...(opts.canSign
      ? {
        // `ieee-p1363` IS the raw `r || s` encoding a JWS needs, so no DER
        // conversion is involved on this path (unlike KMS, which only speaks DER).
        sign: async (input: Buffer) => crypto.sign('sha256', input, { key: privateKey, dsaEncoding: 'ieee-p1363' }),
      }
      : {}),
  };
}
