apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki.pipeline-builder.local:3100
    isDefault: true
    editable: false
    jsonData:
      maxLines: 1000
