// Copyright 2026 Pipeline Builder Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Drift guard for the four gateway `nginx.conf` copies (docker, minikube, ec2,
 * eks).
 *
 * Unlike jwt.js / metrics.js (four byte-identical copies, guarded in
 * bringup-contract.test.ts), nginx.conf genuinely differs per substrate: docker + minikube terminate TLS themselves,
 * ec2 + eks sit behind an ALB and recover the client from X-Forwarded-For, the
 * k8s targets address services by cluster DNS, and ec2/eks move the admin
 * consoles into admin-uis.conf. Everything ELSE — every API route, its
 * rewrite, its buffering/timeout treatment — must be identical, or a route that
 * works locally 404s / buffers / times out in production (the SSE log-export
 * location existed only in docker until this test found it).
 *
 * So the files are PARSED (comments dropped, directives tokenized), normalized
 * by the declared per-target parameters below, and compared structurally. Any
 * difference must be declared in TARGET_SPECIFIC (with the exact set of targets
 * that carry it) or LOCATION_BODY_VARIES — and a declaration that no longer
 * matches reality fails too, so the allow-list cannot rot.
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { describe, expect, it } from '@jest/globals';
import { REPO_ROOT } from '../src/index.js';

// Jest runs with cwd = `platform/`; the deploy tree is at the repo root.

const TARGETS = ['deploy/local/docker', 'deploy/local/minikube', 'deploy/aws/ec2', 'deploy/aws/eks'] as const;
type Target = typeof TARGETS[number];

const LOCAL: Target[] = ['deploy/local/docker', 'deploy/local/minikube'];
const AWS: Target[] = ['deploy/aws/ec2', 'deploy/aws/eks'];
/** The targets whose ConfigMaps are generated by pb_nginx_config — docker mounts static files. */
const K8S: Target[] = ['deploy/local/minikube', ...AWS];

/**
 * Per-target PARAMETERS: the one value a directive legitimately takes on each
 * substrate. Normalized to a placeholder before comparison — and a target that
 * uses the OTHER substrate's value is left un-normalized, so it shows up as drift.
 */
const TARGET_PARAMS: Record<Target, { clientXff: string; forwardedProto: string }> = {
  // TLS terminates in nginx: append the peer, the scheme is nginx's own.
  'deploy/local/docker': { clientXff: '$proxy_add_x_forwarded_for', forwardedProto: '$scheme' },
  'deploy/local/minikube': { clientXff: '$proxy_add_x_forwarded_for', forwardedProto: '$scheme' },
  // Behind the ALB: real_ip already resolved the client into $remote_addr, and
  // the ALB's X-Forwarded-Proto is the truth ($scheme would say "http").
  'deploy/aws/ec2': { clientXff: '$remote_addr', forwardedProto: '$http_x_forwarded_proto' },
  'deploy/aws/eks': { clientXff: '$remote_addr', forwardedProto: '$http_x_forwarded_proto' },
};

type Scope = 'main' | 'http' | 'server' | 'location';

/** Declared target-specific directives/blocks: exactly these targets carry them. */
const TARGET_SPECIFIC: { scope: Scope; item: string; targets: Target[]; why: string }[] = [
  { scope: 'main', item: 'pid /tmp/nginx.pid;', targets: ['deploy/local/docker'], why: 'compose runs nginx as UID 101; the default pid path is root-only' },
  { scope: 'http', item: 'resolver 127.0.0.11 valid=30s ipv6=off;', targets: ['deploy/local/docker'], why: 'Docker embedded DNS' },
  { scope: 'http', item: 'resolver kube-dns.kube-system.svc.cluster.local valid=30s ipv6=off;', targets: ['deploy/local/minikube', ...AWS], why: 'cluster DNS' },
  { scope: 'http', item: 'js_import registry_auth from registry-auth.js;', targets: AWS, why: 'registry token-realm rewrite for the public /v2/ route' },
  { scope: 'http', item: 'include /etc/nginx/real-ip.conf;', targets: AWS, why: 'trusted ALB CIDRs, generated per deploy' },
  { scope: 'http', item: 'include /etc/nginx/ask-upstream.conf;', targets: K8S, why: 'ASK_SERVICE_HOST/PORT, rendered by pb_nginx_config; docker has no config generator' },
  { scope: 'http', item: 'real_ip_header X-Forwarded-For;', targets: AWS, why: 'client IP behind the ALB' },
  { scope: 'http', item: 'real_ip_recursive on;', targets: AWS, why: 'client IP behind the ALB' },
  { scope: 'http', item: 'map $http_cookie $pb_cookie_without_console', targets: AWS, why: 'admin-uis.conf strips the console cookie' },
  { scope: 'http', item: 'include /etc/nginx/rustfs-console.conf;', targets: AWS, why: "the RustFS console's own `server { listen 9001; }` (or its 404 stub) — a server, so it is included at http level, unlike admin-uis.conf" },
  { scope: 'http', item: 'server { listen 8080; server_name localhost; return 301 https://$host:8443$request_uri; }', targets: LOCAL, why: 'local targets terminate TLS: plain :8080 only redirects' },
  { scope: 'server', item: 'listen 8443 ssl;', targets: LOCAL, why: 'local TLS termination' },
  { scope: 'server', item: 'server_name localhost;', targets: LOCAL, why: 'local TLS termination' },
  { scope: 'server', item: 'ssl_certificate /etc/nginx/certs/nginx.crt;', targets: LOCAL, why: 'local TLS termination' },
  { scope: 'server', item: 'ssl_certificate_key /etc/nginx/certs/nginx.key;', targets: LOCAL, why: 'local TLS termination' },
  { scope: 'server', item: 'ssl_protocols TLSv1.3 TLSv1.2;', targets: LOCAL, why: 'local TLS termination' },
  { scope: 'server', item: 'ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;', targets: LOCAL, why: 'local TLS termination' },
  { scope: 'server', item: 'ssl_prefer_server_ciphers off;', targets: LOCAL, why: 'local TLS termination' },
  { scope: 'server', item: 'listen 8080;', targets: AWS, why: 'the ALB terminates TLS and forwards plain HTTP' },
  { scope: 'server', item: 'server_name _;', targets: AWS, why: 'the ALB terminates TLS and forwards plain HTTP' },
  { scope: 'server', item: 'include /etc/nginx/admin-uis.conf;', targets: AWS, why: 'admin consoles are opt-in (admin-uis.conf vs admin-uis-disabled.conf)' },
  { scope: 'location', item: '/grafana/', targets: LOCAL, why: 'inline admin console (aws: admin-uis.conf)' },
  { scope: 'location', item: '/pgadmin/', targets: LOCAL, why: 'inline admin console (aws: admin-uis.conf)' },
  { scope: 'location', item: '/mongo-express/', targets: LOCAL, why: 'inline admin console (aws: admin-uis.conf)' },
  { scope: 'location', item: '/kiali/', targets: ['deploy/local/minikube'], why: 'Istio console; docker has no mesh (aws: admin-uis.conf)' },
  { scope: 'location', item: '/v2/', targets: AWS, why: 'public registry endpoint for off-cluster docker clients' },
];

/** Locations present everywhere whose BODY differs per target, and why. */
const LOCATION_BODY_VARIES: Record<string, string> = {
  // Local targets resolve the registry lazily through a variable so nginx
  // still boots when the registry container is absent; aws always runs it.
  '/registry/': 'lazy upstream variable on local targets',
  // ASK_SERVICE_HOST/PORT are honoured through a generated `upstream pb_ask`
  // block, which only the pb_nginx_config targets can render. On docker the host
  // is the compose service name, fixed by the compose file, so there is no knob
  // to honour and the literal stays.
  '~ ^/api/ask(/.*)?$': 'generated pb_ask upstream on the k8s targets; docker keeps the compose service name',
};

// -- A minimal nginx config parser --------------------------------------------

interface Directive { name: string; args: string[]; block?: Directive[] }

function tokenize(src: string): string[] {
  const out: string[] = [];
  let i = 0;
  while (i < src.length) {
    const c = src[i];
    if (/\s/.test(c)) { i++; continue; }
    if (c === '#') { while (i < src.length && src[i] !== '\n') i++; continue; }
    if (c === '{' || c === '}' || c === ';') { out.push(c); i++; continue; }
    if (c === '"' || c === "'") {
      let j = i + 1;
      while (j < src.length && src[j] !== c) { if (src[j] === '\\') j++; j++; }
      out.push(src.slice(i, j + 1));
      i = j + 1;
      continue;
    }
    let j = i;
    while (j < src.length && !/\s/.test(src[j]) && !'{};'.includes(src[j])) j++;
    out.push(src.slice(i, j));
    i = j;
  }
  return out;
}

function parse(tokens: string[]): Directive[] {
  let i = 0;
  const block = (): Directive[] => {
    const ds: Directive[] = [];
    while (i < tokens.length) {
      if (tokens[i] === '}') { i++; return ds; }
      const words: string[] = [];
      while (i < tokens.length && tokens[i] !== ';' && tokens[i] !== '{') words.push(tokens[i++]);
      if (i >= tokens.length) throw new Error(`unterminated directive: ${words.join(' ')}`);
      const [name, ...args] = words;
      if (tokens[i++] === ';') ds.push({ name, args });
      else ds.push({ name, args, block: block() });
    }
    return ds;
  };
  return block();
}

function serialize(ds: Directive[], target: Target): string {
  const p = TARGET_PARAMS[target];
  return ds.map((d) => {
    // Cluster-DNS service names ↔ compose service names.
    let args = d.args.map((a) => a.replace(/\.pipeline-builder\.svc\.cluster\.local/g, ''));
    if (d.name === 'proxy_set_header' && args[0] === 'X-Forwarded-For' && args[1] === p.clientXff) args = [args[0], '<client-xff>'];
    if (d.name === 'proxy_set_header' && args[0] === 'X-Forwarded-Proto' && args[1] === p.forwardedProto) args = [args[0], '<forwarded-proto>'];
    const head = [d.name, ...args].join(' ');
    return d.block ? `${head} { ${serialize(d.block, target)} }` : `${head};`;
  }).join(' ');
}

interface Model { main: string[]; http: string[]; server: string[]; locations: Map<string, string>; regexOrder: string[] }

/**
 * The RustFS console's server block, which the LOCAL targets inline into
 * nginx.conf and the AWS targets keep in nginx/rustfs-console.conf. It listens on
 * :9001 and carries `location`s of its own, so it must be held apart from the
 * gateway server or the model below sees two gateways and every API route looks
 * target-specific.
 */
const isConsoleServer = (d: Directive) => d.name === 'server' && !!d.block?.some((c) => c.name === 'listen' && c.args[0] === '9001');

function model(target: Target): Model {
  const ds = parse(tokenize(readFileSync(join(REPO_ROOT, target, 'nginx/nginx.conf'), 'utf-8')));
  const http = ds.find((d) => d.name === 'http');
  if (!http?.block) throw new Error(`${target}: no http block`);
  const consoleSrv = http.block.find(isConsoleServer);
  const gateways = http.block.filter((d) => d.name === 'server' && !isConsoleServer(d) && d.block?.some((c) => c.name === 'location'));
  if (gateways.length !== 1) throw new Error(`${target}: expected exactly one gateway server, found ${gateways.length}`);
  const gw = gateways[0].block!;
  const locs = gw.filter((d) => d.name === 'location');
  return {
    main: ds.filter((d) => d.name !== 'http').map((d) => serialize([d], target)),
    http: http.block.filter((d) => d !== gateways[0] && d !== consoleSrv).map((d) => serialize([d], target)),
    server: gw.filter((d) => d.name !== 'location').map((d) => serialize([d], target)),
    locations: new Map(locs.map((d) => [d.args.join(' '), serialize(d.block ?? [], target)])),
    regexOrder: locs.filter((d) => d.args[0] === '~' || d.args[0] === '~*').map((d) => d.args.join(' ')),
  };
}

const models = Object.fromEntries(TARGETS.map((t) => [t, model(t)])) as Record<Target, Model>;

/** Items of a scope, keyed so a `map … {` block matches its declared head. */
function itemsOf(t: Target, scope: Scope): string[] {
  return scope === 'location' ? [...models[t].locations.keys()] : models[t][scope];
}

function declaredFor(scope: Scope, item: string) {
  return TARGET_SPECIFIC.find((d) => d.scope === scope && (item === d.item || item.startsWith(`${d.item} {`)));
}

const short = (ts: readonly string[]) => ts.map((t) => t.split('/').pop()).sort();

describe('nginx.conf cross-target drift', () => {
  it.each(['main', 'http', 'server', 'location'] as Scope[])('every %s-level difference is a declared target-specific item', (scope) => {
    const all = new Set(TARGETS.flatMap((t) => itemsOf(t, scope)));
    const undeclared: string[] = [];
    for (const item of all) {
      const carriers = TARGETS.filter((t) => itemsOf(t, scope).includes(item));
      if (carriers.length === TARGETS.length) continue;
      const decl = declaredFor(scope, item);
      if (!decl || short(decl.targets).join() !== short(carriers).join()) {
        undeclared.push(`${item.slice(0, 160)}  — only in [${short(carriers).join(', ')}]${decl ? `, declared for [${short(decl.targets).join(', ')}]` : ''}`);
      }
    }
    expect(undeclared).toEqual([]);
  });

  it('every declared target-specific item still exists in exactly its declared targets', () => {
    const stale = TARGET_SPECIFIC.filter((d) => {
      const carriers = TARGETS.filter((t) => itemsOf(t, d.scope).some((i) => i === d.item || i.startsWith(`${d.item} {`)));
      return short(carriers).join() !== short(d.targets).join();
    }).map((d) => `${d.scope}: ${d.item}`);
    expect(stale).toEqual([]);
  });

  it('every location shared by all targets has the same body (after per-target parameters)', () => {
    const drifted: Record<string, Record<string, string>> = {};
    for (const [key, body] of models[TARGETS[0]].locations) {
      if (!TARGETS.every((t) => models[t].locations.has(key)) || key in LOCATION_BODY_VARIES) continue;
      const bodies = TARGETS.map((t) => models[t].locations.get(key)!);
      if (bodies.some((b) => b !== body)) drifted[key] = Object.fromEntries(TARGETS.map((t, i) => [t, bodies[i]]));
    }
    expect(drifted).toEqual({});
  });

  it('each LOCATION_BODY_VARIES entry really varies (otherwise drop the exemption)', () => {
    for (const key of Object.keys(LOCATION_BODY_VARIES)) {
      const bodies = new Set(TARGETS.map((t) => models[t].locations.get(key)));
      expect({ key, varies: bodies.size > 1, everywhere: !bodies.has(undefined) }).toEqual({ key, varies: true, everywhere: true });
    }
  });

  it('regex locations (first-match-wins) appear in the same order everywhere', () => {
    const common = (t: Target) => models[t].regexOrder.filter((k) => TARGETS.every((u) => models[u].locations.has(k)));
    for (const t of TARGETS.slice(1)) expect({ target: t, order: common(t) }).toEqual({ target: t, order: common(TARGETS[0]) });
  });

  it('streams log export unbuffered on every target', () => {
    // The drift this test was written against: docker-only until 2026-09-21.
    for (const t of TARGETS) {
      const body = models[t].locations.get('~ ^/api/observability/logs/(export|raw|tail)$');
      expect({ t, body }).toEqual({ t, body: expect.stringContaining('proxy_buffering off;') });
    }
  });
});

/**
 * Every `include` in nginx.conf has a matching ConfigMap mount.
 *
 * A MISSING INCLUDE FILE IS FATAL TO NGINX, not a warning: it exits with
 * `open() "/etc/nginx/x.conf" failed (2: No such file or directory)` and the whole
 * ingress never starts. That is exactly what shipped when `ask-upstream.conf` was
 * added to nginx.conf and to pb_nginx_config's generated keys, but not to
 * nginx.yaml's volumeMounts — the ConfigMap had the key, the container never saw
 * it, and nginx CrashLooped on every target at once.
 *
 * Checked per target because the mount lists genuinely differ: minikube mounts
 * only nginx.conf plus the generated includes, while the AWS targets also mount
 * admin-uis.conf and real-ip.conf.
 */
describe('nginx.conf includes are all mounted', () => {
  // docker has no k8s/nginx.yaml — its nginx is a compose service with a bind mount.
  it.each(K8S)('%s mounts every /etc/nginx/*.conf it includes', (target) => {
    const conf = readFileSync(join(REPO_ROOT, target, 'nginx/nginx.conf'), 'utf-8');
    const included = [...conf.matchAll(/^\s*include\s+\/etc\/nginx\/([\w.-]+\.conf);/gm)].map((m) => m[1]);
    expect(included.length).toBeGreaterThan(0);
    const dep = readFileSync(join(REPO_ROOT, target, 'k8s/nginx.yaml'), 'utf-8');
    const missing = included.filter((f) => !dep.includes(`subPath: ${f}`));
    expect({
      missing,
      fix: 'nginx.conf includes this file but k8s/nginx.yaml never mounts it. A missing '
        + 'include is a FATAL nginx error, so the pod CrashLoops and the ingress is down. '
        + 'Add a volumeMount with mountPath /etc/nginx/<file> and subPath <file>.',
    }).toEqual({ missing: [], fix: expect.any(String) });
  });

  it('generates every include that is not a committed file', () => {
    // An include whose content is produced at deploy time must be emitted by
    // pb_nginx_config, or the mount resolves to an empty/absent key.
    const sh = readFileSync(join(REPO_ROOT, 'deploy/bin/k8s-resources.sh'), 'utf-8');
    for (const target of K8S) {
      const conf = readFileSync(join(REPO_ROOT, target, 'nginx/nginx.conf'), 'utf-8');
      for (const inc of [...conf.matchAll(/^\s*include\s+\/etc\/nginx\/([\w.-]+\.conf);/gm)].map((m) => m[1])) {
        const committed = existsSync(join(REPO_ROOT, target, 'nginx', inc));
        if (!committed) expect([target, inc, sh.includes(inc)]).toEqual([target, inc, true]);
      }
    }
  });
});

/**
 * The RustFS object-store console — FOUR copies of one server block.
 *
 * It is the only console that cannot be a path on the gateway, so it is the only
 * one with its own port, and that makes it the easiest to get subtly wrong. All of
 * the following were real mistakes caught while writing it, each verified live
 * against rustfs/rustfs:1.0.0 rather than read off a doc:
 *   * a trailing slash on proxy_pass strips the prefix, but the UI bakes
 *     /rustfs/console into its own asset URLs, so every asset 404s;
 *   * RUSTFS_CONSOLE_PREFIX=/rustfs is FATAL ("overlaps a reserved server route");
 *   * nginx's default absolute_redirect sent the browser to the INTERNAL port over
 *     plain http, a downgrade on an https page;
 *   * the console resolves its API from window.location and calls ROOT paths, so
 *     the port must proxy / and not just /rustfs/console/.
 */
describe('rustfs console (:9001)', () => {
  /** The console server for a target, wherever that target keeps it. */
  function consoleServer(target: Target): Directive {
    const file = AWS.includes(target) ? 'nginx/rustfs-console.conf' : 'nginx/nginx.conf';
    const src = readFileSync(join(REPO_ROOT, target, file), 'utf-8');
    const top = parse(tokenize(src));
    const candidates = AWS.includes(target) ? top : (top.find((d) => d.name === 'http')?.block ?? []);
    const srv = candidates.find(isConsoleServer);
    if (!srv) throw new Error(`${target}: no server listening on 9001 in ${file}`);
    return srv;
  }

  const bodyOf = (srv: Directive, loc: string) => {
    const l = srv.block!.find((d) => d.name === 'location' && d.args.join(' ') === loc);
    return l ? serialize(l.block ?? [], 'deploy/aws/eks') : undefined;
  };

  it.each(TARGETS)('%s serves the console on its own port', (target) => {
    const srv = consoleServer(target);
    expect(bodyOf(srv, '/')).toEqual(expect.stringContaining('proxy_pass'));
  });

  it.each(TARGETS)('%s proxies / so the ROOT API paths the UI calls are reachable', (target) => {
    // The UI points its S3 client at the bare origin, so S3 operations use the ROOT
    // path space — ListBuckets is `GET /`, objects are `/<bucket>/...` — with the
    // admin API alongside at `/rustfs/admin/v3/*`. All verified live against the
    // deployed console: a signed `/rustfs/admin/v3/is-admin` answers
    // {"is_admin":true}, while an unprefixed `/is-admin` is read as a bucket name
    // and 404s NoSuchBucket. A `location /rustfs/console/` alone would miss them.
    const locs = consoleServer(target).block!.filter((d) => d.name === 'location').map((d) => d.args.join(' '));
    expect(locs).toContain('/');
  });

  it.each(TARGETS)('%s passes the path through unchanged (no trailing slash on proxy_pass)', (target) => {
    const body = bodyOf(consoleServer(target), '/')!;
    const pass = /proxy_pass ([^;]+);/.exec(body)![1];
    expect({ target, pass, stripsPrefix: pass.endsWith('/') }).toEqual({ target, pass, stripsPrefix: false });
  });

  it.each(TARGETS)('%s redirects bare / relatively, never to the internal port', (target) => {
    const body = bodyOf(consoleServer(target), '= /')!;
    expect(body).toContain('absolute_redirect off;');
    expect(body).toContain('return 302 /rustfs/console/;');
  });

  it.each(TARGETS)('%s only redirects / for browsers — GET / is also S3 ListBuckets', (target) => {
    // The console's own SigV4 client issues ListBuckets (service "s3") against its
    // own origin, and ListBuckets is GET /. An unconditional redirect on `= /`
    // answered that API call with a 302 and silently broke bucket listing, so the
    // redirect is scoped to HTML navigations and everything else proxies through.
    const body = bodyOf(consoleServer(target), '= /')!;
    expect(body).toContain('$http_accept');
    expect(body).toEqual(expect.stringContaining('proxy_pass'));
  });

  it.each(TARGETS)('%s names the console upstream the same way', (target) => {
    expect(bodyOf(consoleServer(target), '/')).toEqual(expect.stringContaining('rustfs-console'));
  });

  it.each(AWS)('%s gates every console request on the platform superadmin check', (target) => {
    const body = bodyOf(consoleServer(target), '/')!;
    expect(body).toContain('auth_request /_pb_admin_console_check;');
    // and the platform credential never reaches RustFS
    expect(body).toContain('proxy_set_header Cookie $pb_cookie_without_console;');
    expect(consoleServer(target).block!.some((d) => d.name === 'location' && d.args.join(' ') === '= /_pb_admin_console_check')).toBe(true);
  });

  it.each(LOCAL)('%s leaves the console ungated, like its other inline consoles', (target) => {
    expect(bodyOf(consoleServer(target), '/')).not.toContain('auth_request');
  });

  it('the two AWS copies are identical, in both the on and off states', () => {
    for (const f of ['rustfs-console.conf', 'rustfs-console-disabled.conf']) {
      const [a, b] = AWS.map((t) => readFileSync(join(REPO_ROOT, t, 'nginx', f), 'utf-8'));
      expect({ f, same: a === b }).toEqual({ f, same: true });
    }
  });

  it('ADMIN_UIS_ENABLED=false serves 404 and never proxies', () => {
    for (const target of AWS) {
      const off = readFileSync(join(REPO_ROOT, target, 'nginx/rustfs-console-disabled.conf'), 'utf-8');
      const srv = parse(tokenize(off)).find(isConsoleServer)!;
      const body = serialize(srv.block!.find((d) => d.name === 'location')!.block ?? [], target);
      expect({ target, body }).toEqual({ target, body: expect.stringContaining('return 404;') });
      expect(off).not.toContain('proxy_pass');
    }
  });

  it('both console configs are swapped by the same flag that swaps admin-uis.conf', () => {
    const sh = readFileSync(join(REPO_ROOT, 'deploy/bin/k8s-resources.sh'), 'utf-8');
    for (const f of ['rustfs-console.conf', 'rustfs-console-disabled.conf', 'admin-uis.conf', 'admin-uis-disabled.conf']) {
      expect([f, sh.includes(f)]).toEqual([f, true]);
    }
  });

  it.each(K8S)('%s publishes the console on its own Service, and keeps rustfs 9000-only', (target) => {
    // :9000 is the S3 data plane and has no UI; the console is a second listener in
    // the same process, so it gets its own Service rather than a port on that one.
    const svc = readFileSync(join(REPO_ROOT, target, 'k8s/rustfs-console.yaml'), 'utf-8');
    expect(svc).toContain('name: rustfs-console');
    expect(svc).toContain('port: 9001');
    const rustfs = readFileSync(join(REPO_ROOT, target, 'k8s/rustfs.yaml'), 'utf-8');
    // the listener must still be switched ON, and the port still declared
    expect(rustfs).toContain('RUSTFS_CONSOLE_ENABLE');
    expect(rustfs).toContain('containerPort: 9001');
    // ...but the data-plane Service must not carry it
    const svcPorts = /kind: Service[\s\S]*?\n  ports:([\s\S]*?)\n  selector:/.exec(rustfs);
    expect({ target, publishes9001: !!svcPorts && /port: 9001/.test(svcPorts[1]) }).toEqual({ target, publishes9001: false });
  });

  it.each(K8S)('%s lets nginx — and only nginx — reach the console port', (target) => {
    const np = readFileSync(join(REPO_ROOT, target, 'k8s/networkpolicy.yaml'), 'utf-8');
    // Scoped to each policy's OWN document. A lazy [\s\S]*? across the whole file
    // happily reaches a `- port: 9001` belonging to a LATER policy, so deleting the
    // one being asserted still passed — verified by deleting it.
    const policy = (name: string) => {
      const doc = np.split(/^---$/m).find((d) => d.includes(`name: ${name}`));
      if (!doc) throw new Error(`${target}: no NetworkPolicy named ${name}`);
      return doc;
    };
    // nginx's own ingress must admit 9001, or the port times out instead of 404ing
    expect(/- port: 9001/.test(policy('allow-nginx-ingress'))).toBe(true);
    // and rustfs must admit nginx on 9001
    expect(/app: nginx[\s\S]*?- port: 9001/.test(policy('allow-rustfs-from-services'))).toBe(true);
    const ist = readFileSync(join(REPO_ROOT, target, 'k8s/istio.yaml'), 'utf-8');
    expect(/name: rustfs-allow[\s\S]*?sa\/nginx[\s\S]*?ports: \["9001"\]/.test(ist)).toBe(true);
  });
});
