[SERVICE]
    Flush        5
    Log_Level    info
    Daemon       off
    Parsers_File parsers.conf

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224
    Tag          ecs.*

[FILTER]
    Name         record_modifier
    Match        *
    Record       cluster fargate
    Record       namespace pipeline-builder

[OUTPUT]
    Name         loki
    Match        *
    Host         loki.pipeline-builder.local
    Port         3100
    Labels       job=fluent-bit
    Label_Keys   $container_name,$source
    Auto_Kubernetes_Labels off
    Line_Format  json
